name: GitHub CI
on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.100'

      - name: Build
        run: |
          dotnet build

      - name: CI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Plugin
          path: |
            ./src/bin/Debug/net6.0/
